---
- name: "Configure Parallel cluster AMI"
  hosts: default
  become: true
  gather_facts: true
  gather_subset: ['kernel']
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - base
    - packages
    - aws_cliv2
    - docker
    - aws_efa
    - nvidia_driver
    - nvidia_docker
    - nvidia_cuda
    - nvidia_gdrcopy
    - nvidia_nccl
    - nvidia_enroot_pyxis
    - aws_efa_ofi
    - aws_lustre
