---
- name: "Add cuda-rhel7 repo for CUDA toolkit"
  command: yum-config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/cuda-rhel7.repo
  args:
    creates: /etc/yum.repos.d/cuda-rhel7.repo

- name: "Install dependencies for CUDA toolkit"
  yum:
    name:
      - "libglvnd-opengl"

- name: "Install CUDA toolkit"
  yum:
    name:
      - "cuda-toolkit-{{ cuda_version }}"
      - "{{ cudnn_version }}"
      - "{{ cudnn_version }}-devel"

- name: Adding CUDA path
  blockinfile:
    path: /etc/profile.d/cuda.sh
    create: yes
    block: |
      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
      export PATH=$PATH:/usr/local/cuda/bin
      export CPATH=${CPATH}:/usr/local/cuda/targets/x86_64-linux/include

- name: yum clean metadata
  ansible.builtin.command:
    cmd: yum clean metadata
