---
- name: "Update kernel"
  ansible.builtin.yum:
    name: 'kernel*'
    state: latest
    lock_timeout: 180
    update_only: yes
    update_cache: true
  when: packages_update

- name: "Reboot system"
  reboot:
  when: allow_reboot

- name: "Update all packages"
  ansible.builtin.yum:
    name: '*'
    state: latest
    exclude: "{{ packages_update_exclude }}"
    update_only: yes
    lock_timeout: 180
  when: packages_update

- name: "Install package install list"
  ansible.builtin.yum:
    name: "{{ packages_install }}"
    state: present
    exclude: "{{ packages_install_exclude }}"
  when: packages_install | length > 0

- name: "Remove package remove list"
  ansible.builtin.yum:
    name: "{{ packages_remove }}"
    state: absent
  when: packages_remove | length > 0
